FROM node:8.1.3

# Making work directory ready for the node application
RUN mkdir /finiciti-service
WORKDIR /finiciti-service
ADD package.json /finiciti-service/package.json

RUN mkdir -p /root/.ssh
ADD id_rsa /root/.ssh/id_rsa
ADD id_rsa.pub /root/.ssh/id_rsa.pub
RUN eval "$(ssh-agent -s)"
RUN ssh-keyscan -H github.com >> /root/.ssh/known_hosts
RUN chmod 0700 /root/.ssh
RUN chmod 0600 /root/.ssh/id_rsa
RUN chmod 0644 /root/.ssh/id_rsa.pub

RUN npm install

RUN rm -rf /root/.ssh

# Copying the project files
ADD . /finiciti-service

# Exposing server port
EXPOSE 5000

# Starting web server
ENTRYPOINT ["node", "dist/index.js"]